### ISSUE TITLE
Feature Request: Instance Editor Locator

### ISSUE THREAD

**Issue by ZeWaka** [SpaiR/StrongDMM#1]
Not sure where to put feature requests, so here it is.

The base BYOND editor has a function to locate instances within a .dmm file by right clicking on the instance and allowing you to jump between all instances of the instance within the map file.

Currently, you can only see the changed instance variables, so it would be great to have parity with the base BYOND editor.

**Comment by SpaiR** [comment]
This is totally fine place for proposals 😃
Yes, that is the one of the BYOND feature I was thinking too. But it was de-scoped since I'm not quite sure how it should look like from the user perspective. BYOND realization, with random jumps and barely noticeable arrow, seems no the right solution. Maybe you have some proposals on it?

**Comment by SpaiR** [comment]
Will be a part of the next release, demo by the link below
https://imgur.com/a/mq6gotQ
