### ISSUE TITLE
Map Saves Corrupt 

### ISSUE THREAD

**Issue by VelonacepsCalyxEggs** [SpaiR/StrongDMM#12]
After saving the map for some reason,
the map file: Erased, Corrupted, Some parts of the map are missing! 
My version : 0.0.10
I hope this problem will be solved!

**Comment by SpaiR** [comment]
Could you please provide more details? Since on my local machine everything is ok, I need more steps about how it occurs so I would be able to reproduce it. Do you work with 
an existed map or with the new one (created by editor)? Does it happens everytime you save the map or sometimes? Information like that will help a lot.

**Comment by TheChosenEvilOne** [comment]
I can confirm this happens, editing large maps for longer periods of time causes some turfs to have the wrong ID or whatever you call it thus you have parts of the map get "corrupted". I lost a map completely because of this.

**Comment by CinderWC** [comment]
Considering that it has been a long time since there has been an update on this issue: Is it still something that can happen?
