### ISSUE TITLE
Multiple Z - Levels - Quality of Life

### ISSUE THREAD

**Issue by Xoxeyos** [SpaiR/StrongDMM#14]
There isn't support for multi - Z levels.

**Comment by SpaiR** [comment]
Actually, absence of multi-z support is a design decision. I've described my motivation about that under the `Disclaimer!` label in project readme. But I'm open to hear arguments why it's important to have it.

**Comment by Crossedfall** [comment]
The simplest reason is that they're becoming more common. I also don't see much credence in saying that they are, "unmaintainable from the perspective of Open Source contribution." Considering that the codebases which are using Multi-Z maps have consistent contributions, I'd say it's pretty maintainable.

**Comment by SpaiR** [comment]
I have my own experience as a ss13 dev and I've met situations when it's become pretty painful to deal with conflicts based on multi-z maps. And here we have the Eris codebase. They have multi-z station map too. And they’ve already been in situations when they should to freeze all map changes because of changes on one layer. For me that's enough to think so.

But I understand your point too. Right now I'm in a process of rewriting of the editor, so I will consider about that feature.

**Comment by monster860** [comment]
The thing about multi-z stations is that the whole station is one single unit. With things like, cent-comm and station being on different z-levels, yeah that should be on different files. However, when you have a single station with multiple floors and they are linked to each other, and where moving tiles around on one layer might cause problems on the upper layer, they should absolutely be the same file.

Anyways, the only thing preventing using multiz in the map editor does is screw over any one who wants to contribute to a codebase that has multiz maps.
