### ISSUE TITLE
Bug: Replacing an object with a turf leads to multiple turfs on a tile

### ISSUE THREAD

**Issue by S34NW** [SpaiR/StrongDMM#159]
### Version

2.6.1

### What happened?

You can place multiple turfs on a tile. Normally this is prevented and the editor will replalce the turf when placing a new one on the same tile, but by replacing an object while a turf is selected you can stack them.

### Reproduction

1. Run StrongDMM
2. Find a tile with non-turf atoms
3. Replace a non-turf atom with a turf
4. You now have multiple turfs on a tile

**Comment by ZeWaka** [comment]
multiple turfs on a tile is legal in BYOND DMMs this isn't a bug

**Comment by S34NW** [comment]
Apologies, it seemed like a bug due to the only way you can actually get two turfs on a tile AFAIK is replacing a non-turf object on a tile with a turf.
If it was a legal move you would expect to be able to just place them without this hacky workaround.

**Comment by SpaiR** [comment]
> Apologies, it seemed like a bug due to the only way you can actually get two turfs on a tile AFAIK is replacing a non-turf object on a tile with a turf. If it was a legal move you would expect to be able to just place them without this hacky workaround.

@S34NW You can place double turfs with the `Add`/`Fill` tool while holding `Alt` key. BYOND editor works in the same way, but vice verse. I've decided that it's more common to replace turf by default and not stack them. Behaviour won't be changed since, as @ZeWaka have said, it's a valid case to place one turf on another.
