### ISSUE TITLE
Feature Request: Delete Instance in Obj Panel

### ISSUE THREAD

**Issue by ghost** [SpaiR/StrongDMM#20]
Hello! First off i would like to say that i really enjoy SDMM right now as it is a very robust tool, even with the current threat of map corruption (Haven't run into it yet).

1.
Would it be possible to get a feature that allows us to delete Instances from the Object Panel, or is that impossible?

~~2.
Would it also be possible to add a new window that shows every change done to the map from the very last time that the map was saved. so i.e a window that chows all area,turf,obj,mob etc changes with the option to undo ANY of them regardless of when said change was made in the list?~~

**Comment by SpaiR** [comment]
Hi, thx for your appreciation!
Yes, I think it will be possible to delete instances right from the Object Panel in the same way BYOND does that. 
About the changes history... For now I can't do any estimation about that. I am not sure how the current history system will behave in a scenario where undo happens with item from the middle of the list.

(it's better to create a separate issue for an idea, since it's handier for resolving and closing issues)

**Comment by SpaiR** [comment]
To simplify progress tracking, I've decoupled the second part of the issue into a separate #30
