### ISSUE TITLE
Feature Request: Toggle between old and new appearance.

### ISSUE THREAD

**Issue by ghost** [SpaiR/StrongDMM#52]
Hello!

After one of the more recent updates the look of StrongDMM seems to have been overhauled.

I personally enjoyed the old look and would really like it if there was an option to toggle between both the new and "Classic" look

**Comment by SpaiR** [comment]
Hi.

I may add such option, but the request itself seems a little "rushed" for me. I mean that styling, coloring and so on is a very subjective topic. Yet if something has changed and you're asking right away to  back "the good old times" - that seems a bit unfair to the new style. Give it a chance. From my point of view it's a matter of the habit. Like the control schema different from the DM editor.

Otherwise I would like to hear a more concrete reason why the "classic" look is preferable.

**Comment by CinderWC** [comment]
I personally feel that the old design felt really sleek, it fit the theme of SS13 from the colours and font and i enjoyed it a lot.

Im not asking for you to rollback to the old theme entirely, just give people an option to toggle between old and new
