### ISSUE TITLE
Feature Request: Eyedropper picker tool

### ISSUE THREAD

**Issue by ghost** [SpaiR/StrongDMM#60]
Kind of like in paint/photostop. A picker that selects everything on a given tile and then any subsequent tile painting you do will make whatever was picked off the initial tile.

Example: I have a tile that has a blood stain and black checkerboard floor on it. If i use the picker on that, then every tile i paint afterward will have the bloodstain and checkerboard floor.

**Comment by SpaiR** [comment]
Not quite sure I can image how it works. What's the difference with simple tile copy-pasting?

**Comment by twoski** [comment]
I guess the biggest use case for it would be selecting the type of tile to use in painting.

For example, if i'm drawing walls then want to swap to drawing white tiles, i have to navigate the list and click on white tile in order to make that the active thing being drawn. With a picker i could just press the picker hotkey, pick the white tile i want to draw, and then draw. It basically would remove a bit of tedium from swapping between different turf types

**Comment by SpaiR** [comment]
Then it's more about "object pallete" tho... 🤔

**Comment by twoski** [comment]
It's a QoL thing that can be solved in several ways, i think having a favorites bar could be very useful though, maybe more useful than a picker tool
