### ISSUE TITLE
[Bug] CentCom.dmm doesn't load

### ISSUE THREAD

**Issue by MrHorizons** [SpaiR/StrongDMM#68]
I wish I had more to this, but I don't. Even copying the .dmm file and changing the name makes the problem continue. There aren't any logs that I can find, so I frankly have no idea what's going on.

**Comment by SpaiR** [comment]
The problem is here https://github.com/yogstation13/Yogstation/blob/b01b48e41bcf98f330d6e2fb82afe2cac2ab1b07/code/game/mecha/combat/reticence.dm#L18

Color definition for that object is invalid. Specifically, color variable can accept rgb hex (not rgba, which is used on that line) or matrix to define rgba color. Last two digits are redundant, color should look like this: `#878787`. http://www.byond.com/docs/ref/#/atom/var/color

There is nothing with the editor and you should fix it in your codebase.

Btw, your issue description is out of context. I've checked your profile to understand which codebase you are talking about. But if you expect someone help to resolve your problem, then you should provide more details to that someone about things by yourself.
